sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gflza9anaJzMNJydZwfNOr1UV/uhH7vw/DBOf8zXDLEQ/iUxA434aDKlIkjKlA07mxzfgaRWk9vHjXm/Ms0R9FupDxU/3trAqhYqZA/tx1Cwn0NQe+HLu2Pm+5rHFDcPQSAX6AYI1Mt6JM45eTEr9QakXByK/JJRbshPaGQYS4WveWMwbnuch/Mib5DBsmOdi0fTOmn6XeIfjMETYZHXLYMn0qcKlw4QXH2SG7r95NRWq25akipUeXHVrIUCU4FuTaFnYyZsPWulOiE1KlX6EUj/Prz39bi97kyY/9SQMB2PDVqoq5ZG+IJOQPKe2VHi/+gfjuDexXq88F5sJpzAa+KjXEUqZZ1cyy4nyE/aKeEEObZChPAuHB1MjvTHTDZwm/i5mAP2mw6/UdxRgzR4LS8m8FOiekyL96i5D3WmjJ1Hv6aKUASRQ48hi2jX2Tq9K9HhdJzHrYhwJiWcMRXtN4QSpaMd6AEEJRwbv5q4+e+oHh2K1tpi74CtnexejxrGJkwfiT+r2SX3W+7t+8HaghVc3knLTYd4769oLTNp9QxRxUTtvGNrpqPW6nFZOBR9xyGao4dbuTQ01C1QjLYE5YoRte9eMgn8b70+E4dmA2k3EyszOAVf50M2xekC9rX9U8OOpXgHe1+t/wX4pZnvZIhy6J/F0JHKo7BWMUOpKQI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Observations-By-Mr.-Dooley_4729
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy